#!/bin/sh
SLACK_URL="https://hooks.slack.com/services/XXXXXXXXX/XXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXX"
SLACK_CHANNEL="ticket"
SLACK_USER="slackuser"
SLACK_EMOJI=":hear_no_evil"
YT_BASE_URL="http://youtrack.url"
YT_USER="username"
YT_PASS="password"
LIMIT=10
DATA_DIR=~
DEBUG=0
CURL=1
